# Generated by Django 2.0.3 on 2018-03-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCombo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_combo', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='address',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.AddField(
            model_name='menulist',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menulist', to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='menucombo',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menucombo', to='restaurants.Restaurant'),
        ),
        migrations.AddField(
            model_name='rating',
            name='menucombo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='restaurants.MenuCombo'),
            preserve_default=False,
        ),
    ]
