# Generated by Django 2.0.3 on 2018-03-23 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('restaurant_rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.Menu')),
            ],
        ),
    ]
