# Generated by Django 2.0.3 on 2018-03-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='restaurant_rate',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
