# Generated by Django 2.0.3 on 2018-03-23 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20180324_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurant_rate',
            new_name='_restaurant_rate',
        ),
    ]
