# Generated by Django 2.0.3 on 2018-03-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20180324_0347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='_restaurant_rate',
            new_name='restaurant_rate',
        ),
        migrations.AddField(
            model_name='menucombo',
            name='menu_combo_rate',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
