# Generated by Django 2.0.3 on 2018-03-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20180324_0431'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['restaurant_rate']},
        ),
    ]
