# Generated by Django 2.0.3 on 2018-03-29 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20180324_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='menucombo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menucombo', to='restaurants.MenuCombo'),
        ),
    ]
