# Generated by Django 2.0.3 on 2018-03-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20180329_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-restaurant_rate']},
        ),
    ]
