# Generated by Django 2.0.3 on 2018-03-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_auto_20180330_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menucombo',
            options={'ordering': ['-menu_combo_rate']},
        ),
    ]
